// Generated by scripts/generate-task-prompts.mjs. Do not edit manually.
import prompt0 from "@/tasks/clock/prompt.md";
import prompt1 from "@/tasks/recorder/prompt.md";
import prompt2 from "@/tasks/weather-card/prompt.md";
import prompt3 from "@/tasks/stock-panel/prompt.md";
import prompt4 from "@/tasks/click-fireworks/prompt.md";
import prompt5 from "@/tasks/neon-countdown/prompt.md";
import prompt6 from "@/tasks/particle-gravity/prompt.md";
import prompt7 from "@/tasks/cheetah-trophy-run/prompt.md";
import prompt8 from "@/tasks/dslr-camera/prompt.md";
import prompt9 from "@/tasks/schwarzschild-black-hole/prompt.md";
import prompt10 from "@/tasks/carwash-decision/prompt.md";

export const taskPrompts: Record<string, string> = {
  "clock": prompt0,
  "recorder": prompt1,
  "weather-card": prompt2,
  "stock-panel": prompt3,
  "click-fireworks": prompt4,
  "neon-countdown": prompt5,
  "particle-gravity": prompt6,
  "cheetah-trophy-run": prompt7,
  "dslr-camera": prompt8,
  "schwarzschild-black-hole": prompt9,
  "carwash-decision": prompt10
};
